Repository guardian/grid, pull requests merged in 2019-06, with the labels that each got.

#2578 Make EPA processor not require an exact match on Credit
  common-lib/src/main/scala/com/gu/mediaservice/lib/cleanup/SupplierProcessors.scala
Labels: metadata

#2574 Show progress for batch operations
  kahuna/public/js/components/gr-add-label/gr-add-label.js
  kahuna/public/js/components/gr-batch-export-original-images/gr-batch-export-original-images.js
  kahuna/public/js/components/gr-info-panel/gr-info-panel.js
  kahuna/public/js/components/gr-photoshoot/gr-photoshoot.js
  kahuna/public/js/edits/service.js
  kahuna/public/js/search/results.html
  kahuna/public/js/search/results.js
  kahuna/public/js/services/api/leases.js
  kahuna/public/js/services/label.js
  kahuna/public/js/services/photoshoot.js
  kahuna/public/js/usage-rights/usage-rights-editor.js
  kahuna/public/js/util/batch-tracking.js
  kahuna/public/stylesheets/main.css
Labels: UX

#2568 added initial support for tiff image types
  build.sbt
  common-lib/src/main/scala/com/gu/mediaservice/lib/aws/S3.scala
  common-lib/src/main/scala/com/gu/mediaservice/lib/imaging/ImageOperations.scala
  common-lib/src/main/scala/com/gu/mediaservice/model/ImageType.scala
  cropper/app/lib/Crops.scala
  cropper/test/lib/CropsTest.scala
  image-loader/app/lib/ImageLoaderConfig.scala
  image-loader/app/lib/imaging/FileMetadataReader.scala
  image-loader/app/lib/imaging/MimeTypeDetection.scala
  image-loader/app/model/ImageUpload.scala
  image-loader/test/resources/flag.tif
  image-loader/test/resources/flower.tif
  image-loader/test/resources/lighthouse.tif
  image-loader/test/scala/lib/imaging/FileMetadataReaderTest.scala
  image-loader/test/scala/lib/imaging/MimeTypeDetectionTest.scala
  media-api/app/controllers/MediaApi.scala
  media-api/app/lib/ImageResponse.scala
Labels: imaging

#2583 Update to Getty excludedCollections
  common-lib/src/main/scala/com/gu/mediaservice/lib/config/UsageRightsConfig.scala
Labels: configuration

#2579 Use imagemagick for tiff image operations
  common-lib/src/main/scala/com/gu/mediaservice/lib/imaging/ImageOperations.scala
  common-lib/src/main/scala/com/gu/mediaservice/lib/imaging/im4jwrapper/ImageMagick.scala
  cropper/app/lib/Crops.scala
  image-loader/app/model/ImageUpload.scala
Labels: imaging
